### PR TITLE
(maint) expose `git` as an experimental subcommand

### LINKED ISSUE #328: Expose other executables into main bin directory
I want to use the git that ships with the pdk but it is nested inside a private directory.

/opt/puppetlabs/pdk/private/git/bin

I also want to use gem, irb, and ruby and any other executables that get shipped with gems

### PR DESCRIPTION
**Pull request by DavidS**
Fixes #328

### CODE REVIEW

**Comment by scotje** [comment]
Perhaps we should consider a more generic helper like `pdk shell` (name TBD) that just adds things to the users PATH? (Possibly a command they could just add to their profile?) Make it so that by default we still don't expose the bundled tools but if they really want to opt-in to using them, we provide a helper for setting it up.

**Comment by DavidS** [comment]
That still leaves people in a bind of either reconfiguring their environment (with unknown future repercussions), or not having access to the tooling.

My long-term wish would be to have a minimal `pdk vcs update/commit/upload` workflow that integrates well with existing repo hosting solutions (gitlab, github (enterprise), TFS, etc.). Until we can design/build that, we can expose the tooling we have as subcommands with little effort.

I'd also like to see CRI grow a subcommand that doesn't require the `--`. that would help for this, as well as `pdk bundle`.

**Comment by rodjek** [comment]
> I'd also like to see CRI grow a subcommand that doesn't require the --. that would help for this, as well as pdk bundle.

My [PR](https://github.com/ddfreyne/cri/pull/62) was merged into Cri, so if we update to the latest version and add `skip_option_parsing` to the command definition, we can get rid of the `--` mess.

**Comment by rodjek** [comment]
Added another commit that updates to the latest version of Cri and changes the command to skip option parsing.

```
asmodean :0: puppet/pdk (git:git-subcommand → DavidS {2} U:2!)$ bin/pdk new module foo --skip-interview
pdk (INFO): Creating new module: foo
pdk (INFO): Module 'foo' generated at path '/home/tsharpe/code/puppet/pdk/foo', from template 'https://github.com/puppetlabs/pdk-module-template'.
pdk (INFO): In your module directory, add classes with the 'pdk new class' command.
asmodean :0: puppet/pdk (git:git-subcommand → DavidS {2} U:2 ?:1!)$ cd foo
asmodean :0: pdk/foo (git:git-subcommand → DavidS {2} U:2 ?:1!)$ ../bin/pdk git init .
Initialized empty Git repository in /home/tsharpe/code/puppet/pdk/foo/.git/
asmodean :0: pdk/foo (git:master ?:17!)$ ../bin/pdk git add .
asmodean :0: pdk/foo (git:master S:18!)$ ../bin/pdk git commit -m "Initial commit"
[master (root-commit) 2d9279c] Initial commit
 18 files changed, 653 insertions(+)
 create mode 100644 .fixtures.yml
 create mode 100644 .gitattributes
 create mode 100644 .gitignore
 create mode 100644 .gitlab-ci.yml
 create mode 100644 .pmtignore
 create mode 100644 .project
 create mode 100644 .rspec
 create mode 100644 .rubocop.yml
 create mode 100644 .travis.yml
 create mode 100644 .yardopts
 create mode 100644 CHANGELOG.md
 create mode 100644 Gemfile
 create mode 100644 README.md
 create mode 100644 Rakefile
 create mode 100644 appveyor.yml
 create mode 100644 metadata.json
 create mode 100644 spec/default_facts.yml
 create mode 100644 spec/spec_helper.rb
asmodean :0: pdk/foo (git:master)$ ../bin/pdk git log -3
commit 2d9279c954c5043a3839504d5cce3207fb321d6b
Author: Tim Sharpe <tim@sharpe.id.au>
Date:   Fri Nov 10 11:42:16 2017 +1100

    Initial commit
```

If we want to go with this, the fixup commit should be squashed into the maint commit.

**Comment by DavidS** [comment]
Rebased and fixed README, and `pdk bundle`

**Comment by DavidS** [comment]
This depends on #466.

**Comment by bmjen** [comment]
We discussed this in Triage, and we don't want to expose the internal git.

**Pull request closed without merging**
