### PR TITLE
(SDK-244) Add basic ruby validation acceptance tests.

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by DavidS** [comment]
A little bit of everything.

**Comment by DavidS** [comment]
updated with fixed rubocop excludes and disable the Layout/IndentHeredoc cop for ruby 2.1

**Comment by DavidS** [comment]
rebased on master to remove duplicate commits

**Comment by scotje** [comment]
From appveyor results:

```
Installing puppet-module-win-dev-r2.1 0.0.6
Gem::InstallError: beaker requires Ruby version >= 2.2.5.
An error occurred while installing beaker (3.3.0), and Bundler cannot continue.
Make sure that `gem install beaker -v '3.3.0'` succeeds before bundling.
In Gemfile:
  puppet-module-win-system-r2.1 was resolved to 0.0.6, which depends on
    beaker-module_install_helper was resolved to 0.1.4, which depends on
      beaker
```

Not sure if that's what is causing the other failures...

**Comment by rodjek** [comment]
@DavidS The specs being introduced look good, but it looks like the changes to introduce the spinner are breaking the build? Might be best to split that work out into a separate branch.

**Comment by DavidS** [comment]
@rodjek I can't figure out what's going on here - I think @scotje was working on some of the ruby 2.1 issues? maybe?? 

You can take the tests as they are into your branch, and put up the resultant feature work in parallel.

**Comment by scotje** [comment]
Oy, what a can of worms. I hope things are in a better place on the other side of this though.

**Comment by bmjen** [comment]
This LGTM, there are some things that need to be cleaned up. But that's for another PR. Time to put this one to bed.

**Pull request merged**
