### PR TITLE
(MAINT) Disable parallel unit package testing specs on Windows

### PR DESCRIPTION
**Pull request by scotje**
The parallel_tests gem seems to be having trouble invoking Ruby
correctly on Windows right now, need to debug this but for now hopefully
this gets the build passing again.

### CODE REVIEW

**Comment by scotje** [comment]
Green (!) build with this and https://github.com/puppetlabs/pdk-vanagon/pull/274: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/PDK/view/adhoc/job/platform_pdk_adhoc_pdk-int-sys-testing_adhoc/131/

**Comment by DavidS** [comment]
Great. I just can't read. the acceptance tests here are still and were ever failing because puppet-module-gems pulls in litmus/bolt for ruby 2.5:
```
  1) puppet version selection in a new module when requesting --puppet-version 5.5.22 Command "pdk validate --puppet-version 5.5.22" exit_status is expected to eq 0
     Failure/Error: its(:exit_status) { is_expected.to eq(0) }
       
       expected: 0
            got: 1
       
       (compared using ==)
       
       Dumping stderr output:
       
       pdk (INFO): Using Ruby 2.5.8
       pdk (INFO): Using Puppet 5.5.22
       pdk (INFO): Running all available validators...
       pdk (FATAL): Fetching gem metadata from https://rubygems.org/.......
       Resolving dependencies......
       
       Bundler could not find compatible versions for gem "facter":
         In Gemfile:
           puppet (= 5.5.22) was resolved to 5.5.22, which depends on
             facter (> 2.0.1, < 4)
       
       puppet-module-posix-dev-r2.5 (~> 1.0) was resolved to 1.0.2, which depends
       on
       rspec-puppet-facts (>= 1.10.0, < 3) was resolved to 2.0.1, which depends
       on
               facter
       
       Bundler could not find compatible versions for gem "mocha":
         In Gemfile:
       puppet-module-posix-dev-r2.5 (~> 1.0) was resolved to 1.0.2, which depends
       on
             mocha (>= 1.0.0, < 1.2.0)
       
       puppet-module-posix-dev-r2.5 (~> 1.0) was resolved to 1.0.2, which depends
       on
       puppetlabs_spec_helper (>= 2.9.0, < 3.0.0) was resolved to 2.16.0, which
       depends on
               mocha (~> 1.0)
       
       Bundler could not find compatible versions for gem "puppet":
         In Gemfile:
           puppet (= 5.5.22)
       
       puppet-module-posix-system-r2.5 (~> 1.0) was resolved to 1.0.0, which
       depends on
             puppet_litmus (~> 0.20.0) was resolved to 0.20.0, which depends on
               bolt (>= 2.0.1, < 3.0.0) was resolved to 2.7.0, which depends on
                 puppet (>= 6.11.0, < 7)
```

I'm gonna go emergency-release puppet-module-gem with litmus not available on ruby 2.5 (as 2.0, being a breaking change) and then pdksync all the modules with a change to use ruby 2.7 for acceptance testing and the new puppet-module-gem release. yey :-|

**Comment by DavidS** [comment]
except that this is not entirely accurate either. puppet5 ships on ruby 2.4 (see https://puppet.com/docs/puppet/5.5/about_agent.html) , so the tests running on ruby 2.5 here are not good.

**Comment by DavidS** [comment]
Now the previously passing test_pdk_as_library task is failing:
```
PDK::Module::Convert
  .invoke
    instantiates a new object with the provided options and calls #run
  .new
    when an error is raised from TemplateDir
      reraises the error as a CLI error (FAILED - 1)
    when there are no changes to apply

We need to create the metadata.json file for this module, so we're going to ask you 4 questions.
If the question is not applicable to this module, accept the default option shown after each question. You can modify any answers at any time by manually updating the metadata.json ile.

[Q 1/4] If you have a Puppet Forge username, add it here.
We can use this to upload your module to the Forge when it's complete.
--> (travis) 

```

The only difference in installed gems is a bundler patch-level bump (compared to [Jesse's passing build](https://travis-ci.com/github/puppetlabs/pdk/builds/215819278) from earlier in this PR)

**Comment by DavidS** [comment]
turns out that bundler version really was the culprit. Only waiting for the final acceptance tests to wrap up, then I'll go ahead and merge this and the vanagon changes

**Pull request merged**
