### PR TITLE
Lazier load

### PR DESCRIPTION
**Pull request by rodjek**
Replaces #734 as I can't push changes to that PR for some reason

### CODE REVIEW

**Comment by glennsarti** [comment]
Changes look good!

Some basic tests

Before:
```
Command                     Average       Min       Max
-------                     -------       ---       ---
pdk --help                2.2320389 2.1870754 2.2865134
pdk convert --help 2.20508016666667 2.1799404 2.2225689
pdk config get     2.23941233333333 2.2206996  2.266939
```

After:
```
Command                     Average       Min       Max
-------                     -------       ---       ---
pdk --help         1.83902276666667  1.791677    1.8933
pdk convert --help        1.8104119 1.7821958 1.8381726
pdk config get     1.79916796666667 1.7801964 1.8154091
```

Ref - Test Script:
``` powershell
$commands = @(
  'pdk --help',
  'pdk convert --help',
  'pdk config get'
)

$commands | ForEach-Object {
  $cmd = $_
  $result = @((Measure-command { & bundle exec $cmd }).TotalSeconds)
  $result += (Measure-command { & bundle exec $cmd }).TotalSeconds
  $result += (Measure-command { & bundle exec $cmd }).TotalSeconds
  $rollup = $result | Measure-Object -Average -Minimum -Maximum
  [PSCustomObject]@{
	'Command' = $_;
	'Average' = $rollup.Average;
	'Min' = $rollup.Minimum;
	'Max' = $rollup.Maximum;
  }
} | ft
```

**Comment by glennsarti** [comment]
Ping @logicminds

**Comment by rodjek** [comment]
Still in progress, there's a few files to clean up yet.

**Comment by logicminds** [comment]
looks good to me.  A 20% speed bump might be a 1-2 second speed bump on windows with antivirus.

**Comment by glennsarti** [comment]
Results now:

``` text
Command                     Average       Min       Max
-------                     -------       ---       ---
pdk --help         1.56041463333333 1.5368589 1.5966301
pdk convert --help 1.70375293333333 1.6802888 1.7317406
pdk config get     1.88964556666667 1.8735396  1.901208
```

Slight increase in pdk config get by 0.1s

Also note that these figures are prone to CPU contention e.g. when running a video program in background I got:

``` text
Command                     Average       Min       Max
-------                     -------       ---       ---
pdk --help         3.03996763333333 2.6154305 3.8839271
pdk convert --help 2.99774086666667 2.6227179 3.3622857
pdk config get     2.80889206666667 2.5851717  2.970882
```

**Comment by glennsarti** [comment]
Even still this is ready to merge!

**Pull request merged**
