### PR TITLE
Add new role/profile command

### PR DESCRIPTION
**Pull request by nabertrand**
Allow roles and profiles to be created in site/role and site/profile

RSpec tests will require the directories to be added to .fixtures.yml:
```
---
fixtures:
  symlinks:
    profile: "#{source_dir}/site/profile"
    role: "#{source_dir}/site/role"
```
Not sure if there is an easy way to make sure these get added. Maybe just include them in the template by default?

### CODE REVIEW

**Comment by scotje** [comment]
@nabertrand Thank you so much for contributing to the PDK!

I'm not sure if you saw our announcement, but earlier this week we opened a new repository for open-source planning and design of new PDK features and functionality. We are asking that "substantial" new features run through this lightweight design process before we implement/merge them. The new repository is at https://github.com/puppetlabs/pdk-planning and the README in that repository explains the process.

I think this PR qualifies as a "substantial" enough addition that I'm going to ask that we go through a design/RFC process before we consider this PR for merging. Let me know if I can answer any questions or provide any assistance with the RFC process.

Also I want to apologize for the unfortunate timing of us rolling out this new process right before you opened this PR that you have probably been working on for a while. Our goal with the RFC process for more substantial features is to make sure everyone has a chance to provide feedback on a design and to avoid contributors having to do significant amounts of work or re-work on PRs without knowing whether or not their changes are likely to be accepted.

Thanks again for your contribution!

**Comment by nabertrand** [comment]
@scotje - I think the new RFC process sounds like a great idea. I'd be glad to set up an RFC PR, but it seems to me like this ties into the existing roadmap goal of supporting control repos. I see issue https://github.com/puppetlabs/pdk-planning/issues/10, but not an RFC related to it. How do you think I should proceed?

**Comment by scotje** [comment]
@nabertrand Yeah, perhaps we should work to flesh out https://github.com/puppetlabs/pdk-planning/issues/10 with more detailed workflows demonstrating how PDK would be invoked to add a role or profile to an existing control repo. Then all of that could be integrated into a complete control-repo RFC which we were going to start working on soon anyway.

**Comment by scotje** [comment]
Closing this for now, we will revisit as part of control-repo authoring support down the line.

**Pull request closed without merging**
