### PR TITLE
 (PDK-506) pdk new provider

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by DavidS** [comment]
This requires https://github.com/puppetlabs/pdk-templates/pull/13 to work.

**Comment by DavidS** [comment]
Currently this still needs two manual interventions to work:

* Add the `.sync.yml`, as shown below
* Point the `puppet-resource_api` gem towards the git repo at https://github.com/puppetlabs/puppet-resource_api

The configuration in `.sync.yml` will remain for the forseeable future. The gem/git fix will vanish as soon as I release a new version of the gem (immanent). This can be merged if the code passes muster.

```
david@davids:~/git$ ~/git/pdk/bin/pdk new module example --skip-interview --template-url=/home/david/git/pdk-templates 
pdk (INFO): Creating new module: example
pdk (INFO): Module 'example' generated at path '/home/david/git/example', from template '/home/david/git/pdk-templates'.
pdk (INFO): In your module directory, add classes with the 'pdk new class' command.
david@davids:~/git$ cd example/
david@davids:~/git/example$ cp ../archive/example/.sync.yml .
david@davids:~/git/example$ cat .sync.yml 
---
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-resource_api'
spec/spec_helper.rb:
  mock_with: ':rspec'
(failed reverse-i-search)`conver': git push origin HEAD:unit-test-^Cnversions
david@davids:~/git/example$ ^C
david@davids:~/git/example$ ~/git/pdk/bin/pdk convert --template-url=/home/david/git/pdk-templates --force

----------Files to be modified----------
Gemfile
spec/spec_helper.rb

----------------------------------------

You can find a report of differences in convert_report.txt.

[✔] Resolving Gemfile dependencies.

------------Convert completed-----------

2 files modified.

david@davids:~/git/example$ vi Gemfile
david@davids:~/git/example$ ~/git/pdk/bin/pdk convert --template-url=/home/david/git/pdk-templates --force^C
david@davids:~/git/example$ ~/git/pdk/bin/pdk validate ruby
[✔] Installing missing Gemfile dependencies.
[✔] Checking Ruby code style (**/**.rb).
david@davids:~/git/example$ ~/git/pdk/bin/pdk test unit
[✔] Preparing to run the unit tests.
[✔] Running unit tests.
No examples found.
  Evaluated 0 tests in 0.000324065 seconds: 0 failures, 0 pending.
[✔] Cleaning up after running unit tests.
david@davids:~/git/example$ rm -Rf lib/puppet/ spec/unit/ && ~/git/pdk/bin/pdk new provider foo --template-url=/home/david/git/pdk-templates && ~/git/pdk/bin/pdk validate
pdk (INFO): Creating '/home/david/git/example/lib/puppet/type/foo.rb' from template.
pdk (INFO): Creating '/home/david/git/example/lib/puppet/provider/foo/foo.rb' from template.
pdk (INFO): Creating '/home/david/git/example/spec/unit/puppet/provider/foo/foo_spec.rb' from template.
pdk (INFO): Running all available validators...
[✔] Checking metadata syntax (metadata.json tasks/*.json).
[✔] Checking module metadata style (metadata.json).
[✔] Checking Ruby code style (**/**.rb).
info: task-metadata-lint: ./: Target does not contain any files to validate (tasks/*.json).
info: puppet-syntax: ./: Target does not contain any files to validate (**/**.pp).
info: puppet-lint: ./: Target does not contain any files to validate (**/*.pp).
david@davids:~/git/example$ ~/git/pdk/bin/pdk validate ruby
[✔] Checking Ruby code style (**/**.rb).
david@davids:~/git/example$ ~/git/pdk/bin/pdk test unit
[✔] Preparing to run the unit tests.
[✔] Running unit tests.
  Evaluated 5 tests in 0.014163803 seconds: 0 failures, 0 pending.
[✔] Cleaning up after running unit tests.
david@davids:~/git/example$ 
```

**Comment by bmjen** [comment]
X-Post from the `pdk-templates` PR review. 
https://github.com/puppetlabs/pdk-templates/pull/13#pullrequestreview-90649072

Also, is there a reason why we don't just put those .sync.yml lines into the module skeleton?

**Comment by DavidS** [comment]
I don't think that the gem is ready yet for wide spread release. At one point in the next few months, I expect that to change, but until then, it's something folks will have to carry locally.

Changing the default mock type is something I wanted to do for a long time, but it'll require more work than appropriate for this PR set.

**Comment by DavidS** [comment]
The new version now checks for some preconditions in the `.sync.yml` file. If they are not met, the `pdk new provider` command will point towards the resource api's docs where the necessary changes are described.

**Pull request merged**
