### PR TITLE
Take "operatingsystem_support" parameter from answer.json

### PR DESCRIPTION
**Pull request by me-minus**
fixes for 'Take "operatingsystem_support" parameter from answer.json #1164 '

### CODE REVIEW

**Comment by chelnak** [comment]
@me-minus This looks great. Would it be possible to add a spec test for this too?

**Comment by chelnak** [comment]
@me-minus Looks like we have a few rubocop issues. Can you take a look?

**Comment by chelnak** [comment]
I think those last failures are unavoidable right now. I'll fix up the PR on Monday and get it merged.

Thank you!

**Comment by chelnak** [comment]
@me-minus Looking good! Thanks so much for spending the time on this (and waiting)!

**Review by chelnak — APPROVED** [review]

**Comment by me-minus** [comment]
Have not been able to work on this until now (had a fix-papercuts-day at work) 
If you happen to go to devconf, find the crazy candy Swedes and tell them hello from me

**Comment by moritzdietz** [comment]
Trying to wrap my head around this one, what do I need to put into my answers.json to make this work?

**Comment by me-minus** [comment]
put something like:
"operatingsystem_support": ["Fedora","Windows","Debian based Linux"]
in your answers.json 

The names are taken from lib/pdk/module/metadata.rb

**Comment by moritzdietz** [comment]
Thanks for getting back to my comment. I tried out your suggestion, but no luck.
I'll open a new issue with more details and maybe someone can take a look at which step I'm doing it wrong.

**Pull request merged**
