### PR TITLE
(SDK-313) Update acceptance tests following audit

### PR DESCRIPTION
**Pull request by james-stocks**
Following an audit of the current acceptance tests; there are a number that are acceptable to test at the unit test level.

### CODE REVIEW

**Comment by james-stocks** [comment]
I can probably squash to a single commit; but I thought separate commits might make it easier to review and follow up on feedback for changes

**Comment by scotje** [comment]
Rebased

**Comment by DavidS** [comment]
The new tests are not very unit-y. Are they at least faster?
We can pair tomorrow afternoon for a more in-depth transformation.

**Comment by DavidS** [comment]
oops, I should have rebased this before pushing

**Pull request merged**
