### PR TITLE
(SDK-256) Acceptance tests for metadata validator behavior and output

### PR DESCRIPTION
**Pull request by rodjek**

### CODE REVIEW

**Comment by rodjek** [comment]
Acceptance tests are failing on Windows because we're not currently installing metadata-json-lint on Windows. I've opened a PR on puppetlabs/puppet-module-gems to add it.

**Comment by scotje** [comment]
Rebased on master.

**Comment by rodjek** [comment]
Acceptance tests now passing on Windows \o/

**Comment by DavidS** [comment]
Running this fails when using --format=text (the original SDK-256 content}:

```
david@davids:~/git/pdk/test$ ~/git/pdk/bin/pdk validate --format=text
pdk (INFO): Running all available validators...
[✔] Checking for missing Gemfile dependencies
[✖] Checking metadata.json
/home/david/git/pdk/lib/pdk/report.rb:90:in `block (2 levels) in to_text': private method `puts' called for nil:NilClass (NoMethodError)
Did you mean?  putc
	from /home/david/git/pdk/lib/pdk/report.rb:89:in `each'
	from /home/david/git/pdk/lib/pdk/report.rb:89:in `block in to_text'
	from /home/david/git/pdk/lib/pdk/report.rb:88:in `each'
	from /home/david/git/pdk/lib/pdk/report.rb:88:in `to_text'
	from /home/david/git/pdk/lib/pdk/cli/validate.rb:75:in `block (3 levels) in <module:CLI>'
	from /home/david/git/pdk/lib/pdk/cli/validate.rb:74:in `each'
	from /home/david/git/pdk/lib/pdk/cli/validate.rb:74:in `block (2 levels) in <module:CLI>'
	from /home/david/gems/ruby/2.3.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `run_this'
	from /home/david/gems/ruby/2.3.0/gems/cri-2.9.1/lib/cri/command.rb:264:in `run'
	from /home/david/gems/ruby/2.3.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
	from /home/david/git/pdk/lib/pdk/cli.rb:14:in `run'
	from /home/david/git/pdk/exe/pdk:5:in `<top (required)>'
	from /home/david/git/pdk/bin/pdk:17:in `load'
	from /home/david/git/pdk/bin/pdk:17:in `<main>'
```

**Comment by DavidS** [comment]
the "(maint) Add passing events for files with no puppet-lint problems" commit was already merged in #109, rebasing this to remove the code here. Then I'll merge the work as-is, since the tests pass.

We can deal with --format=text separately.

**Comment by DavidS** [comment]
Turns out I can't read. Rebasing without removing the feature works better :-| :)

This can be merged as soon as CI goes green.

**Pull request merged**
