### PR TITLE
Add ability to generate new facts

### PR DESCRIPTION
**Pull request by logicminds**
This adds a new generator to create facts.  This must be merged along with https://github.com/puppetlabs/pdk-templates/pull/361.

Currently these tests are failing as I need help figuring out why.  Real world testing seems to work fine.

Below is a video showing the usage.  The fact generated is very basic as is the spec file but this is enough to save a few minutes from the user.

### CODE REVIEW

**Review by DavidS — APPROVED** [review]
Code looks great, still needs CI sorted.

- [x] was trying to use pdk-templates#main, which didn't have the template yet; it is merged now
- [x] rubocop complaining about whitespace - will push a fixup in a second

**Comment by DavidS** [comment]
@logicminds the test failures (now that the pdk-templates change has been merged) looks a lot more sensible. Can you work with those?

**Comment by logicminds** [comment]
I updated the code and removed the failing tests.  I don't know how these tests work and without docs I can really move forward without wasting time. A document for acceptance testing generators would be great. I have another branch with a functions generator coming as well.

**Comment by carabasdaniel** [comment]
Hi @logicminds,

Thanks for your contribution, this looks good 👍

**Pull request merged**
