### PR TITLE
(PDK-465) Improve output from spec_prep/spec_clean failures

### PR DESCRIPTION
**Pull request by rodjek**
Example output for a git clone failure from a bad `.fixtures.yml` entry.
```
asmodean :0: pdk/foo (git:pdk-465-2 → origin {2} U:1 ?:1!)$ ../bin/pdk test unit
[✖] Preparing to run the unit tests.
pdk (ERROR): Could not find semantic_puppet gem, falling back to internal functionality. Version checks may be less robust.
pdk (ERROR): Cloning into 'spec/fixtures/modules/notexist'...
pdk (ERROR): fatal: remote error:
pdk (ERROR):   this/does/not/exist is not a valid repository name
pdk (ERROR):   Email support@github.com for help
pdk (ERROR): rake aborted!
pdk (ERROR): Failed to clone git repository git://github.com/this/does/not/exist.git into spec/fixtures/modules/notexist
pdk (ERROR): /home/tsharpe/.pdk/cache/ruby/2.1.0/gems/puppetlabs_spec_helper-2.3.2/lib/puppetlabs_spec_helper/rake_tasks.rb:165:in `clone_repo'
pdk (ERROR): /home/tsharpe/.pdk/cache/ruby/2.1.0/gems/puppetlabs_spec_helper-2.3.2/lib/puppetlabs_spec_helper/rake_tasks.rb:275:in `block (3 levels) in <top (required)>'
pdk (ERROR): Tasks: TOP => spec_prep
pdk (ERROR): (See full trace by running task with --trace)
[✔] Cleaning up after running unit tests.
pdk (FATAL): Failed to prepare to run the unit tests.
asmodean :0: pdk/foo (git:pdk-465-2 → origin {2} U:1 ?:1!)$
```

### CODE REVIEW

**Comment by rodjek** [comment]
Probably want to strip out some of that rake generated noise from the error output too

**Comment by DavidS** [comment]
Another option would be to make clear that the output shown is not from the PDK itself.

**Comment by rodjek** [comment]
@DavidS, how about this:
 * Added a log message saying that the error is coming from a rake task
 * Padded the rake output with newlines to separate it from the PDK output
 * Removed the PDK logger prefix text from the rake output.

```
asmodean :0: pdk/foo (git:pdk-465-2 → origin {2} U:1 ?:1!)$ ../bin/pdk test unit
[✖] Preparing to run the unit tests.
pdk (ERROR): The spec_prep rake task failed with the following error(s):

Could not find semantic_puppet gem, falling back to internal functionality. Version checks may be less robust.
Cloning into 'spec/fixtures/modules/notexist'...
fatal: remote error:
  this/does/not/exist is not a valid repository name
  Email support@github.com for help
rake aborted!
Failed to clone git repository git://github.com/this/does/not/exist.git into spec/fixtures/modules/notexist
/home/tsharpe/.pdk/cache/ruby/2.1.0/gems/puppetlabs_spec_helper-2.3.2/lib/puppetlabs_spec_helper/rake_tasks.rb:165:in `clone_repo'
/home/tsharpe/.pdk/cache/ruby/2.1.0/gems/puppetlabs_spec_helper-2.3.2/lib/puppetlabs_spec_helper/rake_tasks.rb:275:in `block (3 levels) in <top (required)>'
Tasks: TOP => spec_prep
(See full trace by running task with --trace)

[✔] Cleaning up after running unit tests.
pdk (FATAL): Failed to prepare to run the unit tests.
```

I'd like to get rid of those last 4 lines of output too, but that's best done in puppetlabs_spec_helper itself (have the task exit gracefully rather than using Kernel#abort).

**Comment by DavidS** [comment]
👍 looks class.

**Pull request merged**
