### PR TITLE
(maint) Bump minitar to 0.9

### PR DESCRIPTION
**Pull request by rodjek**

### CODE REVIEW

**Comment by logicminds** [comment]
puppet 6.10 was released prompting this change?

```
commit 39078f12744879a2d022c3d9214c6f19e07cfa45 (origin/5.5.x)
Merge: 2de3c780ce 5cc2575366
Author: Josh Cooper <josh@puppet.com>
Date:   Mon Sep 30 13:06:05 2019 -0700

    Merge pull request #7742 from jtappa/PUP-10013-update-minitar

    (PUP-10013) Update minitar to 0.9
```

**Comment by glennsarti** [comment]
Oh interesting... that was merged into Puppet 5.x, but there's been no 5.x release

**Comment by glennsarti** [comment]
```
 1) puppet version selection in a new module puppet-dev uses the correct puppet env Command "pdk test unit --puppet-dev" exit_status should eq 0
     Failure/Error: its(:exit_status) { is_expected.to eq(0) }

       expected: 0
            got: 256

       (compared using ==)
       pdk test unit --puppet-dev
       pdk (INFO): Using Ruby 2.4.3
pdk (INFO): Using Puppet file://C:\Users\glenn.sarti\AppData\Local/PDK/cache/src/puppet
pdk (FATAL): Failed to generate binstubs for 'rake rspec-core':
Resolving dependencies...
Bundler could not find compatible versions for gem "minitar":
  In snapshot (Gemfile.lock):
    minitar (= 0.9)

  In Gemfile:
puppet-module-win-dev-r2.4 (~> 0.3) x64-mingw32 was resolved to 0.4.2, which
depends on
puppet_pot_generator (~> 1.0) x64-mingw32 was resolved to 1.0.1, which
depends on
        puppet x64-mingw32 was resolved to 6.10.0, which depends on
          minitar (~> 0.6.1) x64-mingw32

puppet-module-win-dev-r2.4 (~> 0.3) x64-mingw32 was resolved to 0.4.2, which
depends on
dependency_checker (~> 0.2) x64-mingw32 was resolved to 0.2.0, which
depends on
puppet_forge (~> 2.2) x64-mingw32 was resolved to 2.3.0, which depends
on
          minitar x64-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.


pdk (FATAL): Unable to install requested binstubs.

     # ./spec/acceptance/version_changer_spec.rb:89:in `block (5 levels) in <top (required)>'
```

**Comment by glennsarti** [comment]
And as per @logicminds commented, that commit is in Master, but not yet released.

**Pull request closed without merging**
