### PR TITLE
Replace facter with facter-ng to run tests

### PR DESCRIPTION
**Pull request by sebastian-miclea**

### CODE REVIEW

**Comment by glennsarti** [comment]
Won't work.  Currently Facter-ng doesn't support older rubies e.g. the trailing ampersand

**Comment by sebastian-miclea** [comment]
> Won't work. Currently Facter-ng doesn't support older rubies e.g. the trailing ampersand

Yeah, we've expected failures, just wanted to have a 'real life' run and have a clear output on what's failing. Thank you for having a look.

**Comment by sebastian-miclea** [comment]
Reopened PR to have builds available.

**Comment by DavidS** [comment]
@sebastian-miclea do you still need this PR? Are you planning on moving this work forward as part of the next PDK release?

**Comment by GabrielNagy** [comment]
Should be superseded by https://github.com/puppetlabs/pdk/pull/941

If we loosen the dependency, Ruby 2.1 will pull Facter 2 as before (since it doesn't support 4), and newer rubies should pull Facter 4.

**Comment by DavidS** [comment]
With the upcoming PDK2 release we're dropping support for anything pre-ruby2.4 anyways.

**Pull request closed without merging**
