### PR TITLE
(FM-8081) pdk new transport

### PR DESCRIPTION
**Pull request by DavidS**
Implementation for https://github.com/puppetlabs/pdk-planning/pull/31
Requires https://github.com/puppetlabs/pdk-templates/pull/251

Rebase of #666

### CODE REVIEW

**Comment by DavidS** [comment]
Just rebased this and now it's passing. no idea what went wrong with #666 :man_shrugging:  :-(

**Comment by davidmalloncares** [comment]
Hey @scotje / @rodjek - could some of you guys give this a review please? :)

**Comment by scotje** [comment]
Sorry, we should have been more communicative, I think the plan was to review/merge this for the next release cycle.

@rodjek @glennsarti what do you all think about whether or not we should leave this in for the July release?

**Comment by rodjek** [comment]
As it's marked as experimental, @jbondpdx shouldn't need to create any docs for it (going by the precedent set by `pdk bundle`), so I don't see any problem with making it part of the July release.

**Comment by rodjek** [comment]
Situations like this add further impetus to getting the UI for `pdk config` prioritised as this is a perfect candidate for releasing a new feature behind a feature flag.

**Comment by davidmalloncares** [comment]
Thanks guys :)

**Pull request merged**
