### PR TITLE
(MAINT) Move all unit tests under spec/unit

### PR DESCRIPTION
**Pull request by scotje**
This simplifies running unit tests with your own rspec invocation
without having to copy the pattern from the rake task.

### CODE REVIEW

**Comment by scotje** [comment]
Some of the renaming was also to comply with rubocop rules.

**Comment by scotje** [comment]
I think it wants them to match is the thing, but it also only complains about files once you touch them in a commit. :)

**Comment by scotje** [comment]
I'll leave this open so that BFS has a chance to weigh in.

**Comment by rodjek** [comment]
:+1: this and `lib/pdk/validators` => `lib/pdk/validate`, `lib/pdk/generators` => `lib/pdk/generate` has been bugging me for a while

**Comment by DavidS** [comment]
👍

remove the relevant exclusions from https://github.com/puppetlabs/pdk/blob/master/.rubocop_todo.yml

**Comment by scotje** [comment]
I think I successfully updated the exclusions.

**Comment by DavidS** [comment]
Looks good to me!

**Pull request merged**
